Repository petretiandrea/plugp100, pull requests merged in 2023-08, with the labels that each got.

#105 feat: Add raw_command to base device
  plugp100/api/base_tapo_device.py
Labels: refactoring

#103 feat: Log raw request and response payloads
  plugp100/common/transport/securepassthrough_transport.py
Labels: enhancement

#107 feat: direct parse power strip children
  plugp100/__init__.py
  plugp100/api/power_strip_device.py
  plugp100/responses/device_state.py
  tests/tapo_test_helper.py
  tests/test_power_strip.py
Labels: enhancement

#109 chore: setup black on ci
  .github/workflows/code-review.yml
  .gitignore
  .pre-commit-config.yaml
  build_tools/build_platform_wheel.py
  build_tools/build_vendoring.py
  build_tools/ci_build_utils.py
  build_tools/rename_wheels.py
  plugp100/__init__.py
  plugp100/api/base_tapo_device.py
  plugp100/api/hub/hub_device.py
  plugp100/api/hub/hub_device_tracker.py
  plugp100/api/hub/s200b_device.py
  plugp100/api/hub/t100_device.py
  plugp100/api/hub/t110_device.py
  plugp100/api/hub/t31x_device.py
  plugp100/api/ledstrip_device.py
  plugp100/api/light_device.py
  plugp100/api/light_effect.py
  plugp100/api/light_effect_preset.py
  plugp100/api/plug_device.py
  plugp100/api/power_strip_device.py
  plugp100/api/tapo_client.py
  plugp100/common/functional/either.py
  plugp100/common/state_tracker.py
  plugp100/common/transport/securepassthrough_transport.py
  plugp100/common/utils/http_client.py
  plugp100/common/utils/json_utils.py
  plugp100/discover.py
  plugp100/encryption/key_pair.py
  plugp100/encryption/tp_link_cipher.py
  plugp100/example.py
  plugp100/requests/handshake_params.py
  plugp100/requests/internal/snowflake_id.py
  plugp100/requests/set_device_info/set_light_color_info_params.py
  plugp100/requests/tapo_request.py
  plugp100/responses/alarm_type_list.py
  plugp100/responses/child_device_list.py
  plugp100/responses/device_state.py
  plugp100/responses/device_usage_info.py
  plugp100/responses/hub_childs/s200b_device_state.py
  plugp100/responses/hub_childs/t100_device_state.py
  plugp100/responses/hub_childs/t110_device_state.py
  plugp100/responses/hub_childs/t31x_device_state.py
  plugp100/responses/hub_childs/trigger_log_response.py
  plugp100/responses/tapo_exception.py
  plugp100/responses/tapo_response.py
  pyproject.toml
  requirements-dev.txt
  requirements-test.txt
  setup.py
  tests/tapo_test_helper.py
  tests/test_hub.py
  tests/test_ledstrip.py
  tests/test_light.py
  tests/test_plug.py
  tests/test_power_strip.py
Labels: ci, style

#110 fix getting result from control_child response
  plugp100/__init__.py
  plugp100/api/tapo_client.py
Labels: bug

#112 feat: session timeout handling
  plugp100/api/base_tapo_device.py
  plugp100/api/hub/hub_device.py
  plugp100/api/hub/s200b_device.py
  plugp100/api/hub/t100_device.py
  plugp100/api/hub/t110_device.py
  plugp100/api/hub/t31x_device.py
  plugp100/api/ledstrip_device.py
  plugp100/api/light_device.py
  plugp100/api/plug_device.py
  plugp100/api/power_strip_device.py
  plugp100/api/tapo_client.py
  plugp100/common/functional/either.py
  plugp100/common/functional/tri.py
  plugp100/common/transport/securepassthrough_transport.py
  plugp100/common/utils/http_client.py
  plugp100/example.py
  plugp100/requests/tapo_request.py
  plugp100/responses/alarm_type_list.py
  plugp100/responses/child_device_list.py
  plugp100/responses/device_state.py
  plugp100/responses/device_usage_info.py
  plugp100/responses/hub_childs/s200b_device_state.py
  plugp100/responses/hub_childs/t100_device_state.py
  plugp100/responses/hub_childs/t110_device_state.py
  plugp100/responses/hub_childs/t31x_device_state.py
  plugp100/responses/hub_childs/trigger_log_response.py
  plugp100/responses/tapo_exception.py
  plugp100/responses/tapo_response.py
  plugp100/responses/time_info.py
  tests/test_button_t310.py
  tests/test_hub.py
  tests/test_ledstrip.py
  tests/test_light.py
  tests/test_plug.py
  tests/test_power_strip.py
  tests/test_sensor_s200b.py
Labels: enhancement
